In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_gaussian_quantiles

In [2]:
# Función de activación sigmoidal y su derivada
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def derivada_sigmoid(x):
    return x * (1 - x)

# Inicialización gaussiana
def inicializacion_gaussiana(shape):
    return 2 * np.random.random(shape) - 1

# Función para calcular el error cuadrático medio (MSE)
def calcular_mse(y_true, y_pred):
    return np.mean(np.square(y_true - y_pred))

def descenso_gradiente(entradas, salidas, pesos_entrada_oculta, pesos_oculta_salida, epocas, tasa_aprendizaje):
    for epoch in range(epocas):
        # Capa de entrada a capa oculta
        capa_oculta_entradas = np.dot(entradas, pesos_entrada_oculta)
        capa_oculta_activacion = sigmoid(capa_oculta_entradas)

        # Capa oculta a capa de salida
        capa_salida_entradas = np.dot(capa_oculta_activacion, pesos_oculta_salida)
        capa_salida_activacion = sigmoid(capa_salida_entradas)

        # Calcular errores
        error = salidas - capa_salida_activacion

        # Retropropagación
        delta_salida = error * derivada_sigmoid(capa_salida_activacion)
        error_capa_oculta = delta_salida.dot(pesos_oculta_salida.T)
        delta_capa_oculta = error_capa_oculta * derivada_sigmoid(capa_oculta_activacion)

        # Actualización de pesos y sesgos
        pesos_oculta_salida += capa_oculta_activacion.T.dot(delta_salida) * tasa_aprendizaje
        pesos_entrada_oculta += entradas.T.dot(delta_capa_oculta) * tasa_aprendizaje

        # Imprimir el MSE cada cierto número de épocas
        if epoch % 1000 == 0:
            mse = calcular_mse(salidas, capa_salida_activacion)
            print(f"Epoch {epoch}, MSE: {mse}")

    return pesos_entrada_oculta, pesos_oculta_salida

In [3]:
# Crear datos para XOR
datos_xor_entrenamiento = pd.read_csv('/content/drive/MyDrive/Practica 11/XOR_trn.csv', header=None)
entradas_xor_entrenamiento = datos_xor_entrenamiento.iloc[:, :-1].values
salidas_xor_entrenamiento = datos_xor_entrenamiento.iloc[:, -1].values.reshape(-1, 1)

datos_xor_prueba = pd.read_csv('/content/drive/MyDrive/Practica 11/XOR_tst.csv', header=None)
entradas_xor_prueba = datos_xor_prueba.iloc[:, :-1].values
salidas_xor_prueba = datos_xor_prueba.iloc[:, -1].values.reshape(-1, 1)

# Inicialización de pesos y sesgos para XOR
np.random.seed(1)
pesos_capa_entrada_oculta_xor = inicializacion_gaussiana((entradas_xor_entrenamiento.shape[1], 3))
pesos_capa_oculta_salida_xor = inicializacion_gaussiana((3, 1))

In [4]:
# Entrenamiento para XOR
epocas_xor = 10000
tasa_aprendizaje_xor = 0.1

pesos_capa_entrada_oculta_xor, pesos_capa_oculta_salida_xor = descenso_gradiente(
    entradas_xor_entrenamiento,
    salidas_xor_entrenamiento,
    pesos_capa_entrada_oculta_xor,
    pesos_capa_oculta_salida_xor,
    epocas_xor,
    tasa_aprendizaje_xor
)

# Imprimir resultados de entrenamiento para XOR
print("\nResultado después del entrenamiento para XOR:")
print(sigmoid(np.dot(sigmoid(np.dot(entradas_xor_entrenamiento, pesos_capa_entrada_oculta_xor)), pesos_capa_oculta_salida_xor)))

Epoch 0, MSE: 1.1382795465220854
Epoch 1000, MSE: 0.8158994454757392
Epoch 2000, MSE: 0.8158888476728918
Epoch 3000, MSE: 0.8158847660994777
Epoch 4000, MSE: 0.8158825581028095
Epoch 5000, MSE: 0.8158811678097506
Epoch 6000, MSE: 0.8158802105248153
Epoch 7000, MSE: 0.8158795108290369
Epoch 8000, MSE: 0.8158789769623562
Epoch 9000, MSE: 0.8158785561766655

Resultado después del entrenamiento para XOR:
[[4.99993316e-01]
 [9.49048284e-13]
 [1.13646660e-06]
 ...
 [9.49059800e-13]
 [1.22338008e-06]
 [4.99992704e-01]]


In [5]:
# Crear datos para Gaussian-quantiles
N = 1000
gaussian_quantiles = make_gaussian_quantiles(mean=None,
                        cov=0.1,
                        n_samples=N,
                        n_features=2,
                        n_classes=2,
                        shuffle=True,
                        random_state=None)

X_gaussian, Y_gaussian = gaussian_quantiles
Y_gaussian = Y_gaussian[:, np.newaxis]

# Inicialización de pesos y sesgos para Gaussian-quantiles
np.random.seed(1)
pesos_capa_entrada_oculta_gaussian = inicializacion_gaussiana((X_gaussian.shape[1], 3))
pesos_capa_oculta_salida_gaussian = inicializacion_gaussiana((3, 1))

# Entrenamiento para Gaussian-quantiles
epocas_gaussian = 10000
tasa_aprendizaje_gaussian = 0.1

pesos_capa_entrada_oculta_gaussian, pesos_capa_oculta_salida_gaussian = descenso_gradiente(
    X_gaussian,
    Y_gaussian,
    pesos_capa_entrada_oculta_gaussian,
    pesos_capa_oculta_salida_gaussian,
    epocas_gaussian,
    tasa_aprendizaje_gaussian
)

# Imprimir resultados de entrenamiento para Gaussian-quantiles
print("\nResultado después del entrenamiento para Gaussian-quantiles:")
print(sigmoid(np.dot(sigmoid(np.dot(X_gaussian, pesos_capa_entrada_oculta_gaussian)), pesos_capa_oculta_salida_gaussian)))

Epoch 0, MSE: 0.26917693531105935
Epoch 1000, MSE: 0.26098791572076413
Epoch 2000, MSE: 0.29093069089692014
Epoch 3000, MSE: 0.2640201863845163
Epoch 4000, MSE: 0.26480402378702456
Epoch 5000, MSE: 0.29958587408970644
Epoch 6000, MSE: 0.2872072691355622
Epoch 7000, MSE: 0.32879823655646145
Epoch 8000, MSE: 0.3256270951924989
Epoch 9000, MSE: 0.3297138617846632

Resultado después del entrenamiento para Gaussian-quantiles:
[[0.62250804]
 [0.64828974]
 [0.45879767]
 [0.56082733]
 [0.5222729 ]
 [0.43078278]
 [0.49241065]
 [0.36289931]
 [0.73073341]
 [0.43682142]
 [0.70784887]
 [0.42773067]
 [0.65041674]
 [0.54754897]
 [0.73808267]
 [0.51786848]
 [0.46708363]
 [0.45460614]
 [0.5353694 ]
 [0.41093845]
 [0.39374612]
 [0.50098337]
 [0.40196391]
 [0.60597096]
 [0.5291398 ]
 [0.46234741]
 [0.39893511]
 [0.71115463]
 [0.69104671]
 [0.66214872]
 [0.34320504]
 [0.45974924]
 [0.66504698]
 [0.52933145]
 [0.71889311]
 [0.63772054]
 [0.53479003]
 [0.44856799]
 [0.5461787 ]
 [0.44314061]
 [0.66357926]
 

In [6]:
# Generación de n partículas aleatorias para Gaussian-quantiles
n_particulas_gaussian = 10
particulas_gaussian = np.random.rand(n_particulas_gaussian, X_gaussian.shape[1])

# Evaluación con las partículas aleatorias para Gaussian-quantiles
capa_oculta_entradas_gaussian = np.dot(particulas_gaussian, pesos_capa_entrada_oculta_gaussian)
capa_oculta_activacion_gaussian = sigmoid(capa_oculta_entradas_gaussian)
capa_salida_entradas_gaussian = np.dot(capa_oculta_activacion_gaussian, pesos_capa_oculta_salida_gaussian)
capa_salida_activacion_gaussian = sigmoid(capa_salida_entradas_gaussian)

# Imprimir resultados de la evaluación con partículas aleatorias para Gaussian-quantiles
print("\nResultado de la evaluación con partículas aleatorias para Gaussian-quantiles:")
print(capa_salida_activacion_gaussian)


Resultado de la evaluación con partículas aleatorias para Gaussian-quantiles:
[[0.71751102]
 [0.73782301]
 [0.75533038]
 [0.71665295]
 [0.71568093]
 [0.6729302 ]
 [0.72297378]
 [0.63732106]
 [0.75461018]
 [0.44551961]]


In [8]:
# Pruebas para XOR
capa_oculta_entradas_prueba_xor = np.dot(entradas_xor_prueba, pesos_capa_entrada_oculta_xor)
capa_oculta_activacion_prueba_xor = sigmoid(capa_oculta_entradas_prueba_xor)
capa_salida_entradas_prueba_xor = np.dot(capa_oculta_activacion_prueba_xor, pesos_capa_oculta_salida_xor)
capa_salida_activacion_prueba_xor = sigmoid(capa_salida_entradas_prueba_xor)

# Imprime resultados de prueba para XOR
print("\nResultado después de las pruebas para XOR:")
print(capa_salida_activacion_prueba_xor)


Resultado después de las pruebas para XOR:
[[2.39458361e-06]
 [4.99993057e-01]
 [1.05167664e-06]
 [1.45588400e-07]
 [1.54977576e-07]
 [5.92643097e-06]
 [4.99991981e-01]
 [4.99993349e-01]
 [3.12896798e-07]
 [4.99994149e-01]
 [2.19987451e-06]
 [7.12049951e-06]
 [4.99992822e-01]
 [4.99991861e-01]
 [4.99991597e-01]
 [1.23056544e-06]
 [3.80990083e-06]
 [4.99992901e-01]
 [9.49047036e-13]
 [9.28669246e-07]
 [4.99994485e-01]
 [1.34894400e-07]
 [4.99992209e-01]
 [2.54086343e-06]
 [4.99994853e-01]
 [4.99990996e-01]
 [4.99990608e-01]
 [1.36235072e-06]
 [3.30322505e-07]
 [5.37037554e-07]
 [2.53194658e-06]
 [9.49060037e-13]
 [8.32192653e-07]
 [9.49057380e-13]
 [9.93868897e-07]
 [8.76318062e-07]
 [9.91308924e-07]
 [9.49054569e-13]
 [5.94082101e-06]
 [7.57702511e-07]
 [3.93017117e-07]
 [9.49047696e-13]
 [1.07321610e-06]
 [3.40296959e-06]
 [4.99992598e-01]
 [4.99993354e-01]
 [9.49062076e-13]
 [4.99993301e-01]
 [1.78672138e-06]
 [9.14959542e-07]
 [4.99994969e-01]
 [9.30513874e-07]
 [1.33262885e-06]
 [

In [9]:
# Pruebas para Gaussian-quantiles
capa_oculta_entradas_prueba_gaussian = np.dot(entradas_xor_prueba, pesos_capa_entrada_oculta_gaussian)
capa_oculta_activacion_prueba_gaussian = sigmoid(capa_oculta_entradas_prueba_gaussian)
capa_salida_entradas_prueba_gaussian = np.dot(capa_oculta_activacion_prueba_gaussian, pesos_capa_oculta_salida_gaussian)
capa_salida_activacion_prueba_gaussian = sigmoid(capa_salida_entradas_prueba_gaussian)

# Imprime resultados de prueba para Gaussian-quantiles
print("\nResultado después de las pruebas para Gaussian-quantiles:")
print(capa_salida_activacion_prueba_gaussian)


Resultado después de las pruebas para Gaussian-quantiles:
[[0.59649977]
 [0.40585214]
 [0.49877697]
 [0.50428685]
 [0.50207495]
 [0.60034463]
 [0.34637365]
 [0.37693659]
 [0.59987821]
 [0.35120712]
 [0.49964134]
 [0.49797362]
 [0.41790143]
 [0.42422109]
 [0.38248449]
 [0.60353964]
 [0.60343425]
 [0.37007713]
 [0.72105996]
 [0.4989715 ]
 [0.40528069]
 [0.60642822]
 [0.32387808]
 [0.59893677]
 [0.41010426]
 [0.4166279 ]
 [0.37236537]
 [0.60422187]
 [0.60569842]
 [0.60295679]
 [0.60384777]
 [0.68058517]
 [0.49911308]
 [0.72252002]
 [0.60296388]
 [0.60861847]
 [0.60265657]
 [0.7336813 ]
 [0.49406681]
 [0.60392539]
 [0.60563303]
 [0.69728355]
 [0.49823311]
 [0.60220169]
 [0.4077675 ]
 [0.38029987]
 [0.75283891]
 [0.38366303]
 [0.60735184]
 [0.60360837]
 [0.3633394 ]
 [0.50073345]
 [0.4993444 ]
 [0.60808517]
 [0.66973373]
 [0.77327382]
 [0.69415516]
 [0.49838812]
 [0.60037148]
 [0.65455165]
 [0.6003059 ]
 [0.60369865]
 [0.60899012]
 [0.40128746]
 [0.50030982]
 [0.66962527]
 [0.5031502 ]
 [0